# Generated by Django 4.0 on 2022-02-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
    ]
