# Generated by Django 4.0 on 2022-02-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='upload',
        ),
    ]
